# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ####################
    # CONSOLE COMMANDS #
    ####################

    # create a new database entry
    app.command_create_db_entry:
        class: App\Command\CreateDatabaseEntry
        arguments: [doctrine.orm.entity_manager]

    # creating alias for RoleHierarchyInterface used in App\Command\UserManagerComplex
    Symfony\Component\Security\Core\Role\RoleHierarchy: '@security.role_hierarchy'

    ################
    # Swift Mailer #
    ################

    app.mail.register:
        class: App\Controller\SecurityController
        arguments:
            - "@swiftmailer.mailer"

    ###################
    # TWIG EXTENSIONS #
    ###################
    #app.twig.extension_custom:
    #    class: App\Service\Twig\AbstractTwigExtension
    #    arguments:
    #        - "@router"
    #        - "@assets.packages"

    _instanceof:
        App\Service\Twig\AbstractTwigExtension:
            tags:
                - { name: twig.runtime }


    ############
    # LISTNERS #
    ############
    App\EventSubscriber\UserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }


    ############
    # SERVICES #
    ############
    app.service.locale:
       class: App\Service\LocaleService
       arguments:
           - "@router"
           - "@request"
